version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/dashboard/frontend"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 10

  - package-ecosystem: "uv"
    directory: "/dashboard/backend"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 10