"""initial schema

Revision ID: 404f21c7cdc8
Revises: 
Create Date: 2026-09-14 13:46:23.551090

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '404f21c7cdc8'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='incidentseverity', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('active', 'awaiting_approval', 'remediating', 'resolved', 'rejected', name='incidentstatus', native_enum=False), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('reasoning_trace', sa.JSON(), nullable=False),
    sa.Column('proposed_action', sa.Enum('restart_pod', 'scale_deployment', 'rollback_deployment', 'toggle_feature_flag', name='actiontype', native_enum=False), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_decisions_incident_id'), 'agent_decisions', ['incident_id'], unique=False)
    op.create_table('audit_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entries_incident_id'), 'audit_log_entries', ['incident_id'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('signal', sa.String(length=255), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_incident_id'), 'detections', ['incident_id'], unique=False)
    op.create_table('policy_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('agent_decision_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.Enum('approved', 'denied', name='policyverdict', native_enum=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('policy_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_decision_id'], ['agent_decisions.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_checks_agent_decision_id'), 'policy_checks', ['agent_decision_id'], unique=False)
    op.create_index(op.f('ix_policy_checks_incident_id'), 'policy_checks', ['incident_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('policy_check_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='approvalstatus', native_enum=False), nullable=False),
    sa.Column('actioned_by', sa.String(length=255), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('actioned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['policy_check_id'], ['policy_checks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_incident_id'), 'approval_requests', ['incident_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_policy_check_id'), 'approval_requests', ['policy_check_id'], unique=False)
    op.create_table('remediation_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('approval_request_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('restart_pod', 'scale_deployment', 'rollback_deployment', 'toggle_feature_flag', name='actiontype', native_enum=False), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'succeeded', 'failed', name='actionstatus', native_enum=False), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_actions_approval_request_id'), 'remediation_actions', ['approval_request_id'], unique=False)
    op.create_index(op.f('ix_remediation_actions_incident_id'), 'remediation_actions', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remediation_actions_incident_id'), table_name='remediation_actions')
    op.drop_index(op.f('ix_remediation_actions_approval_request_id'), table_name='remediation_actions')
    op.drop_table('remediation_actions')
    op.drop_index(op.f('ix_approval_requests_policy_check_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_incident_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_policy_checks_incident_id'), table_name='policy_checks')
    op.drop_index(op.f('ix_policy_checks_agent_decision_id'), table_name='policy_checks')
    op.drop_table('policy_checks')
    op.drop_index(op.f('ix_detections_incident_id'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_audit_log_entries_incident_id'), table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    op.drop_index(op.f('ix_agent_decisions_incident_id'), table_name='agent_decisions')
    op.drop_table('agent_decisions')
    op.drop_table('incidents')
    # ### end Alembic commands ###
