"""make event timestamps timezone aware

Revision ID: d9f4c501aded
Revises: 404f21c7cdc8
Create Date: 2026-09-15 17:04:10.842892

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9f4c501aded"
down_revision: str | Sequence[str] | None = "404f21c7cdc8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("approval_requests") as batch_op:
        batch_op.alter_column(
            "actioned_at",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
    with op.batch_alter_table("incidents") as batch_op:
        batch_op.alter_column(
            "resolved_at",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("incidents") as batch_op:
        batch_op.alter_column(
            "resolved_at",
            existing_type=sa.DateTime(timezone=True),
            type_=postgresql.TIMESTAMP(),
            existing_nullable=True,
        )
    with op.batch_alter_table("approval_requests") as batch_op:
        batch_op.alter_column(
            "actioned_at",
            existing_type=sa.DateTime(timezone=True),
            type_=postgresql.TIMESTAMP(),
            existing_nullable=True,
        )
    # ### end Alembic commands ###
